# Only the distributable configuration may replace the checked-in executable.
if(NOT CONFIG STREQUAL "Release")
    return()
endif()
file(MAKE_DIRECTORY "${DESTINATION}")
file(COPY_FILE "${SOURCE}" "${DESTINATION}/lwconvert.exe" ONLY_IF_DIFFERENT)
file(MAKE_DIRECTORY "${DESTINATION}/licenses")
file(COPY_FILE "${THIRD_PARTY}/README.md" "${DESTINATION}/licenses/README.md" ONLY_IF_DIFFERENT)
file(COPY_FILE "${THIRD_PARTY}/libilbm/LICENSE" "${DESTINATION}/licenses/libilbm.txt" ONLY_IF_DIFFERENT)
file(COPY_FILE "${THIRD_PARTY}/stb/LICENSE" "${DESTINATION}/licenses/stb.txt" ONLY_IF_DIFFERENT)
message(STATUS "Win64 converter: ${DESTINATION}/lwconvert.exe")
